export type TabType = 'dashboard' | 'branches' | 'staff' | 'attendance' | 'leaves' | 'sales' | 'payslips';

export type StaffPosition = 'MANAGER' | 'SUPERVISOR' | 'SENIOR_CREW' | 'CREW';
export type StaffStatus = 'ACTIVE' | 'INACTIVE';
export type BranchStatus = 'ACTIVE' | 'INACTIVE';
export type LeaveType = 'MEDICAL' | 'ANNUAL' | 'EMERGENCY' | 'OFF DAY';
export type LeaveStatus = 'PENDING' | 'APPROVED' | 'REJECTED';

export type AttendancePunctuality = 
  | 'ON TIME' 
  | 'LATE' 
  | 'ABSENT' 
  | 'EMERGENCY LEAVE' 
  | 'MEDICAL LEAVE' 
  | 'HALF DAY' 
  | 'PRESENT' 
  | 'ON_LEAVE';

export interface Branch {
  key: string;
  code: string;
  name: string;
  address: string;
  status: BranchStatus;
  createdAt?: number;
  updatedAt?: number;
}

export interface Staff {
  key: string;
  name: string;
  email: string;
  phone?: string;
  position: StaffPosition;
  status: StaffStatus;
  branch?: string;
  source?: string;
  createdAt?: number;
  updatedAt?: number;
}

export interface AttendanceLog {
  key: string;
  empName: string;
  userEmail: string;
  date: string;
  clockIn: string;
  clockOut: string;
  punctualityStatus: AttendancePunctuality;
  remarks?: string;
  durationText?: string;
  hasAttachment?: boolean;
  attachmentUrl?: string;
  attachmentPath?: string;
  attachmentFileName?: string;
  attachmentContentType?: string;
  attachmentBase64?: string;
  statusColor?: string;
  createdByAdmin?: boolean;
  editedByAdmin?: boolean;
  autoGenerated?: boolean;
  timestamp?: number;
  lastModifiedAt?: number;
}

export interface LeaveRequest {
  key: string;
  empName?: string;
  staffName?: string;
  name?: string;
  userEmail: string;
  leaveType: LeaveType;
  status: LeaveStatus;
  startDate: string;
  endDate: string;
  reason: string;
  appliedAt?: number;
  hasAttachment?: boolean;
  mcBase64?: string;
  mcFileName?: string;
  mcContentType?: string;
  updatedByAdminAt?: number;
}

export interface FlavorInventoryItem {
  prevStock: number;
  newStock: number;
  promoFree: number;
  balance: number;
  sold: number;
}

export interface SalesReport {
  key: string;
  cawangan?: string;
  branch?: string;
  date: string;
  submittedBy: string;
  jumlahBag?: string | number;
  bagAyam?: string | number;
  salesCash: number;
  totalDailySales: number;
  catatan?: string;
  createdAt?: number;
  updatedAt?: number;

  platforms?: {
    misi?: number;
    lalamove?: number;
    foodPanda?: number;
    grabFood?: number;
    shopeeFood?: number;
  };

  inventoryTracker?: {
    Cheese?: FlavorInventoryItem;
    Korean?: FlavorInventoryItem;
    Garlic?: FlavorInventoryItem;
    Furikake?: FlavorInventoryItem;
    Togarashi?: FlavorInventoryItem;
    Coleslaw?: FlavorInventoryItem;
    [key: string]: FlavorInventoryItem | undefined;
  };

  qualityAndWastage?: {
    promo10Pcs?: string | number;
    ayamTakHabis?: string | number;
    ayamBusuk?: string | number;
    ayamShort?: string | number;
    review?: string | number;
    loyalKad?: string | number;
  };

  expenses?: {
    minyakMasak?: string | number;
    staffMeal?: string | number;
    gas?: number;
    ais?: number;
    beliBarang?: number;
    minyakKenderaan?: number;
    dobi?: number;
  };
}

export interface PayslipRecord {
  key: string;
  staffName: string;
  staffEmail: string;
  position: string;
  period: string;
  amount: number | null;
  fileName?: string;
  contentType?: string;
  fileData?: string; // base64 string
  uploadedAt: number;
  uploadedBy?: string;
  breakdown?: SMEPayrollBreakdown;
}

export interface PresenceItem {
  email?: string;
  name?: string;
  empName?: string;
  status: 'ONLINE' | 'OFFLINE';
  lastSeen?: number;
}

export interface ActiveSession {
  empName?: string;
  userEmail?: string;
  clockInTime?: number | string;
  punctualityStatus?: string;
  branch?: string;
}

export interface ToastMessage {
  id: string;
  message: string;
  type: 'info' | 'success' | 'error';
}

export interface SMEPayrollBreakdown {
  basicSalary: number;
  absentDays: number;
  presentDays: number;
  dailyRate: number;
  absentDeduction: number;
  grossSalary: number;
  epfEmployee: number;
  socsoEmployee: number;
  eisEmployee: number;
  totalDeductions: number;
  netSalary: number;
}

export interface StaffSummaryMetrics {
  weekdayBalance: number;
  weekendBalance: number;
  totalBalance: number;
  unpaidDays: number;
}
